### ISSUE TITLE
Create a testing template for HOPR Chat

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-testing#10]
- [ ] Create a spreadsheet listing a series of tasks and cases to follow to document a testing run against a specific version of HOPR Chat.

**Comment by 0xjjpa** [comment]
@peterbraden 

> why does the fact that it's stdin stdout prevent us from scripting tests?

Mainly because we wanted to have two `hopr-chat` nodes talking to each other and we could only due to this via Docker, which was not interactive. We decided to scrap testing using `hopr-chat` and focus on testing when `hopr-server` is alive.

> I guess my bigger question is _what_ are we testing?
> 
> If we are simply testing the chat code, we can create unit tests and fake stdin stdout etc.
> 
> If we are smoke testing the entire chat -> hopr -> chat interaction then we need a way to spin up a network of nodes. Or we assume that the testnet is stable enough to smoke test against that.
> 
> I don't believe in manual testing for this, so I definitely think we need CI to run all this.

So `hopr-core` has unit-tests. We are talking about testing some real-world scenarios, like 30 nodes talking to each other. We actually had talked with the `libp2p` about [Testground](https://docs.testground.ai/) but sadly the only implementation is on Go. It would be super neat to have a way to implement an interface in TypeScript using their SDK tho. Asked this already [here](https://github.com/testground/testground/discussions/1086).

So the tl;dr is we want to
- spin X amount of nodes
- ask them to send Y amount of messages between them
- query and ensure the messages were actually delivered (likely via `hopr-server`).

**Comment by nionis** [comment]
Already done.
