### ISSUE TITLE
Setup hopr-core testing w/gRPC server

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-testing#11]
- [ ] Test automatic scaling for `X` amount of nodes.
- [ ] Test specific actions for default methods (i.e. `send`)

**Comment by 0xjjpa** [comment]
@peterbraden This is a more “descriptive” task on what we are trying to achieve. Since we have already unit tests inside `hopr-server`, it's more about building the tooling for spinning, let's say, 10 `hopr-server` nodes, get their address, ask them to send/listen to a bunch of messages and ensuring they got those.

**Comment by nionis** [comment]
Issue no longer relevant.
